### ISSUE TITLE
[Session] 세션 상세 - 발표자 소개

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnights2023_App#138]
## Kind (Required)
- Feature

## Overview (Required)
- 세션 상세 내용에 발표자 소개 영역 추가
~- 디자인 시안이 만들어지기 전이라 추후 업데이트가 필요합니다. (당장 작업할 수 없습니다)~
- [디자인 참고](https://www.figma.com/file/FL7CdEyPjvhkJrtYEHAbXn/2023-Droid-Knights-App-_-KEB?type=design&node-id=120-955&mode=design&t=ghIMEgndGgBYOvY8-0)

* 세션 소개와 같이 발표자 소개를 나타낼 수 있으면 됩니다.

**Comment by Cjsghkd** [comment]
🙋‍♂️

**Comment by wisemuji** [comment]
@Cjsghkd https://github.com/droidknights/DroidKnights2023_App/issues/232 에서 중복된 작업이 진행되고 있어 이 이슈는 닫아두겠습니다. 
혹시 작업을 시작하셨다면 미리 안내드리지 못해 죄송합니다 🙇
