### ISSUE TITLE
[Contributor] 로딩 중에 아이템을 표시하기 위한 Shimmer 효과 

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnights2023_App#144]
## Kind (Required)
- Improvement

## Overview (Required)
- 깃허브 API에서 컨트리뷰터 목록을 가져오는 중에 컨트리뷰터 화면에 아무런 데이터가 표시되지 않음
- 로딩중에 실제 아이템 대신 표시하기 위한 Shimmer 기능 구현

## Question
Q. 라이브러리 사용해도 되나요?
A. 네 사용해도 됩니다.

Q. 반짝이는 효과가 없어도 문제 없나요?
A. 네, 단순 색상의 placeholder를 적용해도 됩니다.

**Comment by yjyoon-dev** [comment]
🙋‍♂️

**Comment by laco-dev** [comment]
@yjyoon-dev 
이슈에 참여해주셔서 감사합니다.
본문에 적은바와 같이 Shimmer는 현업에서 사용중인 일반적인 구현을 적용하셔도 괜찮습니다.

로딩중에 사용자에게 UI 상태를 표시한다 라는 목적을 달성하면 됩니다.
