### ISSUE TITLE
[Main] 다크 모드 기능을 데이터로 관리한다

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnights2023_App#147]
## Kind
- Improvement

## Overview
- 현재 다크모드 기능을 CompositionLocal로 관리하고 있는데 데이터에 저장해서 앱을 재실행 해도 유지되도록 한다
- 기본 값은 항상 라이트모드
- `LocalDarkTheme` --> 

## Etc
- 데이터 저장 방법은 자유롭게 사용 가능

**Comment by JeonK1** [comment]
🙋‍♂️

MainActivity 에서 MutableState<Boolean> 값을 가지고 있다보니 Activity 가 파괴 및 재생산되면 (ex - 화면전환) 선택되어있는 다크테마모드도 풀리는 것 같습니다.

**구현계획**
Boolean 값을 관리하는 것이기에 DataStore 라이브러리르 추가하여, 앱 내 저장소에 보관하고, 
MainActivity 에서 datastore 의 isDarkTheme 값을 flow 로 참조하여, 테마 변경에도 대응할 수 있도록 개선해볼 계획입니다.

**Comment by wisemuji** [comment]
@JeonK1 구현 계획 공유 감사합니다. 

요구사항의 성격은 조금 다르지만 NowInAndroid 앱에서 어떻게 테마 데이터를 관리하고 있는지 참고해보셔도 도움이 될 것 같습니다.
https://github.com/android/nowinandroid/blob/153b34fd50c0eb98fb42b298be7525080a1e43bd/core/datastore/src/main/java/com/google/samples/apps/nowinandroid/core/datastore/NiaPreferencesDataSource.kt#L112

관련해서 리포팅된 버그 이슈도 첨부합니다 🙏 
https://github.com/droidknights/DroidKnights2023_App/issues/164
