### ISSUE TITLE
[Setting] 오픈소스 라이센스 명시

### ISSUE THREAD

**Issue by wisemuji** [droidknights/DroidKnights2023_App#155]
## Kind (Required)
- Improvement

## Overview (Required)
<img width="507" alt="image" src="https://github.com/droidknights/DroidKnights2023_App/assets/32327475/cb26266e-a641-457f-9be5-4974b824d75a">

- https://www.figma.com/file/FL7CdEyPjvhkJrtYEHAbXn/2023-Droid-Knights-App-_-KEB?type=design&node-id=442%3A784&mode=design&t=Kp3P9CxJNXIw5d4m-1
- 설정 상단에 오픈소스 라이센스를 확인할 수 있는 카드를 추가한다.
- OSS licenses-plugin 액티비티를 연결한다.

## Links

- https://developers.google.com/android/guides/opensource

**Comment by KwakEuiJin** [comment]
🙋‍♂️
