### ISSUE TITLE
각 탭에서 스크롤이 되지않습니다

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2023_App#162]
**Overview (Required)**
- 화면 분할 혹은 세로가 좁은 화면에서 스크롤이 되지 않아서 컨텐츠 확인이 안됨

**Steps To Reproduce**

컨텐츠 노출이 좁은 상태

1. 앱 실행
2. 각 탭에서 스크롤 시도

**Screenshots**

![Screenshot_20230801_223440](https://github.com/droidknights/DroidKnights2023_App/assets/1534926/98e2ffdf-6543-4cc7-9b77-0724fb70855d)

**Comment by JeonK1** [comment]
🙋‍♂️
