### ISSUE TITLE
네트워크가 연결안된 상태로 컨트리뷰트 화면 진입시 앱이 종료 됨

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2023_App#166]
**Overview (Required)**
- 네트워크가 안되는 환경에서 특정 화면을 진입할 수 없습니다.

**Steps To Reproduce**

1. 네트워크 Off로 설정
2. 앱 실행
3. 컨트리뷰트 화면 진입
4. 앱이 종료됨

**Expected behavior**
앱 강제 종료외의 현상이 노출되어야합니다.

**Screenshots**

https://github.com/droidknights/DroidKnights2023_App/assets/1534926/d41e736f-e94c-4db8-8294-c127d026a229

**Comment by JeonK1** [comment]
🙋‍♂️
네트워크를 사용하는 화면들의 UiState 에서 Error State 도 만들어주며, Network 에서 데이터를 가져올 때 flow.catch { } 을 통해 에러가 발생한 경우 Error State 반환 및 UI 에서 처리하도록 수정할 예정이며,
Error State 시의 UI 처리는 Loading 상황에서의 UI 처리와 동일하게 보여주지만 SnackBar 를 에러타입에 따라 "네트워크 연결이 원활하지 않습니다", "알 수 없는 오류가 발생하였습니다" 로 노출할 계획입니다.

다만 #225 이슈를 통해 HomeViewModel 에서 Loading 에 대한 UiState 가 추가될 수 있음을 우려하여 해당 이슈가 종료된 후에 진행하고자 합니다.
