### ISSUE TITLE
후원사 이미지를 클릭하면 브라우저로 홈페이지가 연결된다

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnights2023_App#182]
## Kind (Required)
- Feature

## Overview (Required)
- 후원사 이미지를 클릭하면 연결된 홈페이지로 연결되어야 한다.
- url: `sponsor.homepage`

<img width="429" alt="image" src="https://github.com/droidknights/DroidKnights2023_App/assets/32327475/c5cffdf0-619a-487c-bca8-1539806891b3">

**Comment by yjyoon-dev** [comment]
🙋‍♂️
