### ISSUE TITLE
README의 libs.versions.toml 클릭시 404 페이지

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnights2023_App#195]
## Kind (Required)
- documents

## Overview (Required)
- `libs.versions.toml` 경로가 잘못 잡혀있어 404 페이지로 출력됩니다.
- 실제 경로에 맞게 수정이 필요합니다.

**Comment by JaesungLeee** [comment]
🙋‍♂️

**Comment by wisemuji** [comment]
@JaesungLeee 도와주셔서 감사합니다!
