### ISSUE TITLE
[북마크] 북마크한 세션 목록을 확인할 수 있어야 한다

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnights2023_App#198]
## Kind (Required)
- Feature

## Overview (Required)
- [디자인](https://www.figma.com/file/FL7CdEyPjvhkJrtYEHAbXn/2023-Droid-Knights-App-_-KEB?type=design&node-id=455-2220&mode=dev)
- 북마크 정보를 가져와서 UI로 출력합니다.
- 디자인 시안에 있는 내용을 완벽하게 소화하지 않아도 됩니다.
- 편집 기능은 제외합니다.

<img width="304" alt="image" src="https://github.com/droidknights/DroidKnights2023_App/assets/32327475/fb6347b4-6e53-4ee5-b514-1b36b98fc175">

**Comment by toastmeister1** [comment]
🙋‍♂️

**Comment by wisemuji** [comment]
@toastmeister1 앱 개발을 도와주셔서 감사합니다! 도움이 필요하시면 언제든 말씀해주세요 :)
