### ISSUE TITLE
[북마크] 북마크를 변경하면 UI를 표시한다

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnights2023_App#201]
## Kind (Required)
- Design
- Feature

## Overview (Required)
- [디자인](https://www.figma.com/file/FL7CdEyPjvhkJrtYEHAbXn/2023-Droid-Knights-App-_-KEB?type=design&node-id=455%3A1772&mode=design&t=Kp3P9CxJNXIw5d4m-1)
- 북마크를 추가하거나 삭제할 때 아래 UI와 같은 형태로 사용자에게 알린다.
- 시안을 반드시 소화하지 않아도 됩니다. (괜찮다고 생각하면 충분합니다)

<img width="294" alt="image" src="https://github.com/droidknights/DroidKnights2023_App/assets/32327475/e0f070ce-0684-4bf6-afe0-d67d1258f648">

**Comment by gowoon-choi** [comment]
🙋‍♀️

**Comment by laco-dev** [comment]
@gowoon-choi 
드로이드 나이츠 이슈에 참여해주셔서 감사합니다.

UI 구현이 어렵다면, 토스트와 같은 간단한 형태로 만들어 주셔도 괜찮습니다. 🙏🏻
