### ISSUE TITLE
[세션] 변경된 세션 시간표 반영

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnights2023_App#207]
## Overview (Required)
- 전체적인 세션 시간 변경에 따라 관련 데이터 수정 필요

```
11:00 ~ 11:30
11:45 ~ 12:15
13:25 ~ 14:10
14:25 ~ 14:55
15:10 ~ 15:40
16:00 ~ 16:45
17:00 ~ 17:30
```

**Comment by wisemuji** [comment]
@laco-dev 
일반 세션 데이터 수정은 https://github.com/droidknights/DroidKnights2023_App/pull/204#issuecomment-1679100559 에서 반영되었습니다. 이 이슈에서는 키노트 데이터 변경만 진행할게요
