### ISSUE TITLE
키노트 세션을 클릭하면 앱이 종료됩니다

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnights2023_App#210]
**Overview (Required)**
- 세션 목록의 키노트 아이템을 클릭하면 앱이 종료됨

**Steps To Reproduce**
1. 세션 목록 이동
2. 키노트 클릭
3. 앱 종료

**Expected behavior**
- 키노트를 클릭해도 앱이 종료되지 않아야 함

**Screenshots**
<img src="https://github.com/droidknights/DroidKnights2023_App/assets/28249981/3488ee27-a7c7-4faa-b50d-6b6c679257b1" width=300/>

**Additional context**
- 키노트의 경우 세션 상세가 불필요하기 때문에 이동할 필요 X

**Comment by koreatlwls** [comment]
🙋‍♀️🙋🙋‍♂️

**Comment by laco-dev** [comment]
@koreatlwls 
드로이드나이츠 이슈에 참여해주셔서 감사합니다.

실제 키노트 데이터 값은 변경하지 않아도 됩니다.
문제가 되는 크래시 현상을 막아주시면 됩니다. 🙏🏻
