### ISSUE TITLE
Composable에서 사용하는 List의 리컴포지션 카운트 줄이기

### ISSUE THREAD

**Issue by taehwandev** [droidknights/DroidKnights2023_App#222]
## composable 함수에 전달되어지는 list 사용시 리컴포지션 카운트가 1 증가합니다.

Immutable 형태로 변경하여 리컴포지션 카운터를 줄여보세요.

힌트) Kotlin collection 사용하기

**Comment by l2hyunwoo** [comment]
🙋‍♂️
