### ISSUE TITLE
[홈] 후원사 카드 로딩 전 노출할 UI 구현

### ISSUE THREAD

**Issue by wisemuji** [droidknights/DroidKnights2023_App#225]
## Kind (Required)

- Improvement

## Overview (Required)

- 현재는 후원사 카드의 데이터가 로딩되며 없던 카드가 갑자기 생기는 동작이 어색합니다.
- 로딩 중 상태를 정의하고 이때 표시할 UI를 구현합니다.
- https://github.com/droidknights/DroidKnights2023_App/issues/144 에서처럼 Shimmer 효과를 적용하셔도 되고 방식은 자유입니다.

## Screenshot 
<img src="https://github.com/droidknights/DroidKnights2023_App/assets/32327475/a07f005b-f526-481b-84b2-49ed5fa6ca8c" width="300" />

**Comment by yuuuzzzin** [comment]
🙋‍♀️🙋🙋‍♂️

**Comment by laco-dev** [comment]
@yuuuzzzin 
이슈에 참여해주셔서 감사합니다.
본문에서 언급된 이슈를 해결한 PR을 참고해주셔도 됩니다. 
- https://github.com/droidknights/DroidKnights2023_App/pull/223
