### ISSUE TITLE
세션 상세정보 화면 디자인 변경

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnights2023_App#232]
## Kind (Required)
- Feature

## Overview (Required)
- 세션 상세 정보 디자인 시안 확정에 따라 관련 기능 수정 작업

```
세션 상세 정보 
기존 태그 : 트랙 / 발표시작시간 
변경 태그 : 트랙 / 발표시작시간 / 카테고리(발표주제) 추가
라이트/다크 동일한 색상의 태그

웹사이트와 동일형식으로 수정 및 구분선 추가
기존 : 내용 / 발표자 이름 사진
변경 : 세션소개 - 내용 / 구분선 / 발표자 이름 사진 / 발표자소개내용
```
<img src="https://github.com/droidknights/DroidKnights2023_App/assets/28249981/976225ee-ac46-46d6-b1c0-fc3eec3ef952" width=360/>

## Links
- 디자인 링크 
: https://www.figma.com/file/FL7CdEyPjvhkJrtYEHAbXn/2023-Droid-Knights-App-_-KEB?type=design&node-id=869-4764&mode=design&t=s4x62iStqWN7sZZe-4

**Comment by sodp5** [comment]
🙋‍♂️

**Comment by laco-dev** [comment]
@sodp5 
이슈에 참여해주셔서 감사합니다.

현재 진행중인 PR에서 관련 화면에 대한 수정이 병행되고 있기 때문에 참고 부탁드립니다.
