### ISSUE TITLE
[세션, 북마크] 세션 목록에서 북마크 여부가 노출된다

### ISSUE THREAD

**Issue by wisemuji** [droidknights/DroidKnights2023_App#236]
## Kind (Required)

- Improvement

## Overview (Required)
- [디자인](https://www.figma.com/file/FL7CdEyPjvhkJrtYEHAbXn/2023-Droid-Knights-App-_-KEB?type=design&node-id=1%3A381&mode=design&t=yPRzUs1C7QlU9prg-1)
- 세션 목록에서 북마크된 세션은 북마크아이콘과 북마크태그가 추가되어 노출한다.
- 북마크되지 않은 세션은 별도의 UI 변경이 없다.
- 세션 상세에서의 데이터 변경사항을 어떻게 감지할지 고민이 필요하다.
<img width="360" alt="image" src="https://github.com/droidknights/DroidKnights2023_App/assets/32327475/6191a36d-ca85-4e81-8b94-7f9e309b20d9">

## Links

- https://github.com/droidknights/DroidKnights2023_App/issues/201 
- https://github.com/droidknights/DroidKnights2023_App/issues/202

**Comment by KwakEuiJin** [comment]
🙋‍♂️

**Comment by wisemuji** [comment]
@KwakEuiJin 감사합니다! 
도움이 필요하시다면 편하게 알려주세요.

**Comment by wisemuji** [comment]
@KwakEuiJin 관련 작업중인 PR도 첨부합니다.

https://github.com/droidknights/DroidKnights2023_App/pull/234
