### ISSUE TITLE
위젯 기능 추가 제안

### ISSUE THREAD

**Issue by jeongth9446** [droidknights/DroidKnights2023_App#259]
## Kind (Required)

- Proposal / Discussion

## Overview (Required)

- 안녕하세요. 드로이드나이트 2023에서 Glance 위젯 관련된 발표를 진행하게 될 정태훈입니다.
- 드로이드나이츠2023 앱에 간단하게 Glance 위젯을 추가하면 어떨까해서 제안드립니다.
- 적용한다면, Glance 위젯의 샘플 앱 역할을 수행하는 동시에, 발표 내용에 대한 실증 사례에 대해 많은 분들이 참고할 수 있을 것 같습니다.
- 일정 상, 디자인이 나오기 까지는 시간이 소요될 거 같아 임의로 작성해본 샘플을 첨부드립니다.

- 적용기능 :
-   앱에서 북마크 추가 시 위젯에 목록 표시
-   위젯에서 타이틀 선택 시 앱 실행

- 검토 중 기능 : 
-    위젯에서 북마크 삭제 버튼 추가
-    위젯에서 북마크 선택 시 앱의 세션 소개 화면으로 이동 

허가를 해주신다면 코드 PR을 드리도록 하겠습니다. 

## Links

-

**Comment by jeongth9446** [comment]
![image](https://github.com/droidknights/DroidKnights2023_App/assets/52663419/24f21f85-e27c-43e3-bf84-a50e1d4072f4)

**Comment by wisemuji** [comment]
@jeongth9446 안녕하세요 태훈님, 반갑습니다 😊 
드로이드나이츠 앱은 개발자들이 편하게 하고 싶은 이슈를 제안해주시고 작업을 진행하실 수 있습니다.

발표를 듣는 참여자 입장에서 여러 의미로 좋은 인사이트를 받을 수 있는 기능이 될 것 같습니다. 앱 사용성 측면에서도 도움이 될 기능으로 보여요.

적용하신 기능만 PR로 올려주셔도 되고 검토중이신 기능도 편하게 작업해주세요.
디자인은 너무 신경쓰지 않으셔도 됩니다.
PR 올려주시면 확인하겠습니다.

**Comment by jeongth9446** [comment]
PR 드렸습니다 확인부탁드립니다.
